# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/naoki/dev/QT/desktop plugin/desktop_plugin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from desktop_plugin.UI.BaseUI.BaseUI import BaseUI


class desktop_plugin_ui(BaseUI):

    def _BindEvent(self, widget: QtWidgets.QWidget):
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 480)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgba(153, 153, 255, 51);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese))
        self.calendarWidget.setGeometry(QtCore.QRect(0, 160, 400, 180))
        self.calendarWidget.setStyleSheet("background-color: rgb(153, 153, 255);\n"
                                          "gridline-color: rgb(102, 102, 102);\n"
                                          "border-color: rgb(153, 153, 153);\n"
                                          "color: rgb(0, 0, 0);\n"
                                          "alternate-background-color: rgb(255, 255, 255);\n"
                                          "selection-background-color: rgb(255, 255, 0);\n"
                                          "selection-color: rgb(51, 204, 102);")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(False)
        self.calendarWidget.setDateEditEnabled(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.weather_label = QtWidgets.QLabel(self.centralwidget)
        self.weather_label.setGeometry(QtCore.QRect(0, 100, 400, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.weather_label.setFont(font)
        self.weather_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.weather_label.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_label.setObjectName("weather_label")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(0, 0, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.system_version_name_label = QtWidgets.QLabel(self.centralwidget)
        self.system_version_name_label.setGeometry(QtCore.QRect(0, 340, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.system_version_name_label.setFont(font)
        self.system_version_name_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.system_version_name_label.setObjectName("system_version_name_label")
        self.system_version_label = QtWidgets.QLabel(self.centralwidget)
        self.system_version_label.setGeometry(QtCore.QRect(0, 360, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.system_version_label.setFont(font)
        self.system_version_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.system_version_label.setObjectName("system_version_label")
        self.cpu_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_label.setGeometry(QtCore.QRect(0, 380, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpu_label.setFont(font)
        self.cpu_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.cpu_label.setObjectName("cpu_label")
        self.cpu_temp_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_temp_label.setGeometry(QtCore.QRect(0, 400, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpu_temp_label.setFont(font)
        self.cpu_temp_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.cpu_temp_label.setObjectName("cpu_temp_label")
        self.system_version_name_output_label = QtWidgets.QLabel(self.centralwidget)
        self.system_version_name_output_label.setGeometry(QtCore.QRect(110, 340, 290, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.system_version_name_output_label.setFont(font)
        self.system_version_name_output_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.system_version_name_output_label.setObjectName("system_version_name_output_label")
        self.cpu_output_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_output_label.setGeometry(QtCore.QRect(110, 380, 290, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpu_output_label.setFont(font)
        self.cpu_output_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.cpu_output_label.setObjectName("cpu_output_label")
        self.system_version_output_label = QtWidgets.QLabel(self.centralwidget)
        self.system_version_output_label.setGeometry(QtCore.QRect(110, 360, 290, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.system_version_output_label.setFont(font)
        self.system_version_output_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.system_version_output_label.setObjectName("system_version_output_label")
        self.memory_label = QtWidgets.QLabel(self.centralwidget)
        self.memory_label.setGeometry(QtCore.QRect(0, 440, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.memory_label.setFont(font)
        self.memory_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.memory_label.setObjectName("memory_label")
        self.cpu_temp_output_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_temp_output_label.setGeometry(QtCore.QRect(110, 400, 290, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpu_temp_output_label.setFont(font)
        self.cpu_temp_output_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.cpu_temp_output_label.setObjectName("cpu_temp_output_label")
        self.cpu_idle_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_idle_label.setGeometry(QtCore.QRect(0, 420, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpu_idle_label.setFont(font)
        self.cpu_idle_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.cpu_idle_label.setObjectName("cpu_idle_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(0, 50, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.cpu_idle_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.cpu_idle_progressBar.setGeometry(QtCore.QRect(110, 425, 280, 15))
        self.cpu_idle_progressBar.setProperty("value", 24)
        self.cpu_idle_progressBar.setStyleSheet(
            "QProgressBar {border: 2px solid grey;border-radius: 5px;background-color: #FFFFFF;text-align: center;}\n"
            "QProgressBar::chunk{background-color: rgba(0, 0, 204, 217);border: 2px solid grey;border-radius: 5px;}")
        self.cpu_idle_progressBar.setObjectName("cpu_idle_progressBar")
        self.memory_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.memory_progressBar.setGeometry(QtCore.QRect(110, 445, 280, 15))
        self.memory_progressBar.setProperty("value", 24)
        self.memory_progressBar.setStyleSheet(
            "QProgressBar {border: 2px solid grey;border-radius: 5px;background-color: #FFFFFF;text-align: center;}\n"
            "QProgressBar::chunk{background-color: rgba(0, 0, 204, 217);border: 2px solid grey;border-radius: 5px;}")
        self.memory_progressBar.setObjectName("memory_progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        super().setupUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weather_label.setText(_translate("MainWindow",
                                              ""))
        self.date_label.setText(_translate("MainWindow", ""))
        self.system_version_name_label.setText(_translate("MainWindow", "系统代号"))
        self.system_version_label.setText(_translate("MainWindow", "系统版本"))
        self.cpu_label.setText(_translate("MainWindow", "CPU型号"))
        self.cpu_temp_label.setText(_translate("MainWindow", "CPU温度"))
        self.system_version_name_output_label.setText(_translate("MainWindow", "system_version_name_output"))
        self.cpu_output_label.setText(_translate("MainWindow", "cpu_output"))
        self.system_version_output_label.setText(_translate("MainWindow", "system_version_output"))
        self.memory_label.setText(_translate("MainWindow", "内存状态"))
        self.cpu_temp_output_label.setText(_translate("MainWindow", "cpu_temp_output"))
        self.cpu_idle_label.setText(_translate("MainWindow", "CPU状态"))
        self.time_label.setText(_translate("MainWindow", ""))
