# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/naoki/dev/QT/Python UI/password_enter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect
from PyQt5.QtWidgets import QDesktopWidget

from desktop_plugin.UI.BaseUI.BaseUI import BaseUI


class password_enter_dialog(BaseUI):
    def _setGeometry(self, widget: QtWidgets.QWidget):
        screen = QDesktopWidget().screenGeometry()
        size = widget.geometry()
        widget.setGeometry(QRect((screen.width() - size.width()) / 2 + screen.left(),
                                 (screen.height() - size.height()) / 2,
                                 size.width(), size.height()))
    
    def _BindEvent(self, widget: QtWidgets.QWidget):
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).clicked.connect(widget.OKButton_Clicked)
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(629, 153)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(270, 101, 341, 41))
        self.buttonBox.setStyleSheet("selection-background-color: rgb(0, 51, 255);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 581, 21))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        super(password_enter_dialog, self).setupUi(Dialog)
        Dialog.setWindowFlags(
            QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请输入root密码"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText('确定')
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText('取消')
